# Generated by Django 5.1.1 on 2024-10-17 12:10

from django.db import migrations

def update_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    site = Site.objects.get(pk=1)
    site.name = 'CPPREV'
    site.domain = 'localhost:8090'
    site.save()
    
    
class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(update_site),
    ]
