# Generated by Django 5.1.1 on 2024-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=11, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
