# Generated by Django 5.1.1 on 2024-10-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_historicomudancaestadorequerimentoinicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicomudancaestadorequerimentoinicial',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estadorequerimentoinicial',
            name='nome',
            field=models.CharField(choices=[('em análise', 'Em Análise'), ('concluído deferido', 'Concluído Deferido'), ('concluído indeferido', 'Concluído Indeferido')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicomudancaestadorequerimentoinicial',
            name='data_mudanca',
            field=models.DateTimeField(),
        ),
    ]
